# Site settings
title: Michael Brown
email: michaelfbrown.88@gmail.com
description: "I'm a front end developer in Washington, D.C. I write CSS for <a href='http://www.jibe.com'>Jibe</a> and learn something new every day."
baseurl: ""
url: "http://mfbrown.github.io"
twitter_username: mfbrown
github_username:  mfbrown

# Build settings
markdown: kramdown
permalink: pretty
